### ISSUE TITLE
getOntologyMetadata gives hardcoded P-Plan metadata

### ISSUE THREAD

**Issue by stain** [dgarijo/Widoco#117]
I tried to use:
```
java -jar ../../Widoco/JAR/widoco-0.0.1-jar-with-dependencies.jar -ontURI http://purl.org/pav/ -getOntologyMetadata -outFolder 3
```

but in the output (Which looks very nice, thank you!) - I get wrong metadata, like:

* The P-Plan ontology
* Authors:
*    http://delicias.dia.fi.upm.es/members/DGarijo#me
*    http://www.isi.edu/~gil/
* This work is licensed under a Creative Commons CC-BY-NC-SA. 
* Revision     1.3

**Comment by dgarijo** [comment]
Hi Stian,
thanks for reporting this bug. It was a small mistake I hadn't realized (I had done all my tests with local ontologies, which worked fine). Now it is fixed in the latest commit. That said, if you want to rerun the script, I recommend you doing the following: 
>java -jar widoco-0.0.1-jar-with-dependencies.jar -ontURI http://purl.org/pav/ -getOntologyMetadata -outFolder 3 -saveConfig configOutFile.

That would save the metadata that Widoco can capture in a config file. If then you edit the config file with the missing metadata and rerun the script with the option -confFile instead of -getOntologyMetadata, you will avoid a lot of time editing the html :)

Thanks to this issue I have realized that I am not capturing the "see also" metadata. I will deal with that in a future release.
