### ISSUE TITLE
No title or authors and empty serializations

### ISSUE THREAD

**Issue by mariapoveda** [dgarijo/Widoco#200]
With this ontology https://github.com/mariapoveda/vicinity-ontology-wot/tree/master/ontology widoco:

.- does not generate title
.- does not get authors
.- does not get the prefix
.- generate empty serializations

**Comment by dgarijo** [comment]
I cannot see any error. I attach what I generate. The only thing that is not being generated is the License name, because I am not using licensius. (the URL points to the correct one):
![onto](https://cloud.githubusercontent.com/assets/1520666/22096601/5c587ae8-ddd1-11e6-9c6a-df8d056f677a.png)
[myDocumentation.zip](https://github.com/dgarijo/Widoco/files/715879/myDocumentation.zip)

**Comment by dgarijo** [comment]
Ah, I used the latest Widoco release (1.2.3) https://github.com/dgarijo/Widoco/releases/latest
