### ISSUE TITLE
Unable to produce content in the 'Introduction' section

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#261]
[Publishers.txt](https://github.com/dgarijo/Widoco/files/1487622/Publishers.txt)

Tried to generate content for 'Introduction' - but it is always showing the placeholder text.

Tried  out all these dc:description   dcterms:description   rdfs:comment   schema:description   skos:note

Can you please advise.

**Comment by dgarijo** [comment]
@kartgk,
at the moment the introduction is not generated from any annotation property. Instead, most of all those properties are used for the abstract. I have given a go and the latest JAR for some reason is not recognizing them. However the latest code does. I will upload a new version when I have the time. 

The reason for description and comment to be considered as the abstract is because the majority of the ontologies use them for short descriptions. Since they appear in a separate category in the best practices, I think I should code a behavior like the one you expect in your ontology. It would also be compatible with what LODE originally does.

**Comment by kartgk** [comment]
Thanks for taking this up. At the very least there should be a way to turn off the placeholder text which doesnt look good if we are showing this to the management :)

**Comment by dgarijo** [comment]
2 options: 
a) comment the line on the index.html that loads the section (look for the introduction). Don't worry about the numbering of sections, the document auto generates them.
b) Once you have an initial version of the ontology, generate the documentation with the -crossRef option. This only updates the cross reference and overview sections (it doesn't even produce an index.html).

I will open an issue to generate docs without any place holder text....

**Comment by pmcb55** [comment]
I just added a PR (#359) to add a new flag to explicitly exclude the introduction section (just to be able to easily remove that placeholder text when generating (rather than having to edit the output of generation)).

**Comment by dgarijo** [comment]
Since the PR has been merged, I will close this issue.
