### ISSUE TITLE
Unable to override license Name

### ISSUE THREAD

**Issue by kartgk** [dgarijo/Widoco#263]
[Publishers.txt](https://github.com/dgarijo/Widoco/files/1490266/Publishers.txt)

The link on the generated License element seems to be right - But on screen it is displaying as 'license name goes here'.   So I tried to override it using config.properties
[config.txt](https://github.com/dgarijo/Widoco/files/1490279/config.txt)

But it still doesnt change the displayed name. Can you please advise.

**Comment by dgarijo** [comment]
When reading the metadata properties from the ontology, you can only extract the license URL or the name, but not both (depending what you assert on the license property). 

If you run the tool with the -licensius flag, in theory it will go to that service and attempt to retrieve the license name. But it is failing quite a bit lately, and now it seems to be down.

If you run the program to get the metadata from the config file, you have to use the "-confFile" flag. However, that will make WIDOCO to not extract metadata from the ontology. Have you tried that? 

I think that I am going to slightly change the tool so if by default you don't have a name for your license but you have the license URI, use the license URI instead of the default text. Would that be sufficient?

**Comment by kartgk** [comment]
I tried with the -confFile and removed licensius and -getOntologyMetadata options. Now I get 

`Error while generating the documentation null`

I m aware of only the dct:license property to specify license URL. How to specify name ?

I guess, when licensius is failing, your solution of showing the URI would do for now.   Thanks for responding diligently and suggesting options.

**Comment by kartgk** [comment]
Didnt know whether this is an issue, so just asking here - How to get the 'Description' section populated - Is it driven by ontology metadata or is expected to be done manually ? ( I tried dc:description, dct, skos.. as mentioned in the best practices page without success )

**Comment by dgarijo** [comment]
@kartgk 
First of all, thanks to you for opening these issues. I have noticed that there is no documentation explaining many of the questions you ask, and I should fix that.

Some comments:
1) I am not aware of a solution for specifying the license name, unfortunately. That is why I accessed Licensius. What I should do within the tool is that instead of just adding "license name goes here" I will add the URI if the name is not known. Probably I will hardcode some of the most popular licenses (apache, MIT, creative commons) to get the names, and for the rest try and access licensius if it works.

2) If you run WIDOCO with the -confFile option, you need to complete all metadata in the configuration file. None will be completed from the ontology. Therefore the tool probably be failing because in your config file there is no URI for the ontology, etc. I suggest you have a look at the default config file https://github.com/dgarijo/Widoco/blob/master/doc/configurationSamples/config/config.properties and complete the properties you like. If you don't want to add something, then I suggest leave it blank.

3) I have talked to the person responsible in Licensius, it should be back on soon.

4) The description section is meant to be completed manually. Here is an example: http://linked.earth/ontology/core/1.2.0/index-en.html#desc. At the moment is not completed from any metadata property. In the future, I would like some sort of example to be automatically added, but that is future work. You can always comment it out from the documentation if you don't want to include it.

**Comment by kartgk** [comment]
Great, thanks for the detailed response. Will take care of the description section manually.

**Comment by kartgk** [comment]
We are trying to use the MIT license. Would help to know what URL to add to dct:license to get this working through licensius. Which one should we be using
https://opensource.org/licenses/MIT
or 
http://purl.org/NET/rdflicense/MIT1.0
Can you please check with the licensius person and let us know.  Would have tried to contact licensius directly, but we are using it through widoco, so thought this would be better.

**Comment by dgarijo** [comment]
I think it is better to use the former. The latter is an identifier used to describe the license metadata. It should be recognized by Licensius. The only issue I can imagine is due to a malfunction of the service.

**Comment by kartgk** [comment]
Used this but no luck.
https://opensource.org/licenses/MIT

This is our published ontology
https://spec.edmcouncil.org/fibo/ontology/master/latest/BE/Corporations/Corporations/

And generated index file
https://spec.edmcouncil.org/fibo/widoco/master/latest/BE/Corporations/Corporations/index-en.html

**Comment by vroddon** [comment]
Hi!
The following URL http://purl.org/NET/rdflicense/MIT1.0 is served with content negotiation. By default, it leads to the most official license source, but if requested RDF it will return the RDF representation _as interpreted by us_ --please note that we are not an authoritative source, but the RDF may help. 

About the reported problem in https://github.com/oeg-upm/licensius/, you can count on the solution to be ready by the end of Wednesday 10th. ---Sorry for the delays, we just landed form the Christmas break..

Regards,
Víctor

**Comment by kartgk** [comment]
@dgarijo I am following up with vroddon ( licensius ) to handle https.  In addition when widoco build is running, i see this error when I run with the --licensius option

-->Could not load license for vocab: connect timed out

why is it trying vocab license. 
[Corporations.txt](https://github.com/dgarijo/Widoco/files/2226788/Corporations.txt)

**Comment by vroddon** [comment]
Received. Tomorrow will try to check this.
Thanks for reporting!

**Comment by dgarijo** [comment]
Since Licensius was updated after reporting this, I will close the issue
