### ISSUE TITLE
Consider schema:domainsInclude and schema:rangesInclude

### ISSUE THREAD

**Issue by dgarijo** [dgarijo/Widoco#274]
When producing documentations
Issue requested by Vladimir Alexiev (@VladimirAlexiev)

**Comment by dgarijo** [comment]
I will have to look at this pull request for LODE: https://github.com/essepuntato/LODE/pull/13 where @VladimirAlexiev has addressed in LODE. However, since I added additional metadata to LODE, I will have to manually incorporate the changes.

**Comment by pyvandenbussche** [comment]
Hi David, great work on the integration and the wizard! 
I agree this functionality is quite pressing as a lot of vocabularies now re-use the loose notion of schema domainsInclude / rangesInclude.

**Comment by VladimirAlexiev** [comment]
Please also consider https://github.com/essepuntato/LODE/issues/15

**Comment by dgarijo** [comment]
@VladimirAlexiev thanks, I will check it out! Some of these I already had added :)

**Comment by VladimirAlexiev** [comment]
Suggested tests: 
- http://data.businessgraph.io/ontology
- http://schema.org
- https://www.w3.org/ns/ssn/ which imports https://www.w3.org/ns/sosa/ which uses domain/rangeIncludes

**Comment by dgarijo** [comment]
@VladimirAlexiev,
ok, I have implemented your changes and will commit soon. Regarding the test ontologies:
1) For the business ontology it works if you remove the annotations on properties made at the end of the document. Since they are declared twice LODE takes them as named individuals. 
2) I tested it on a class with properties (https://schema.org/Book.ttl). It didn't work on the properties because they are rdf:Property instead of owl:ObjectProperty. I tried to add support for rdf:Property, but LODE doesn't recognize it properly. I have no clue why, feedback is welcome. 
3) Works fine (tried on https://www.w3.org/ns/sosa/)

**Comment by VladimirAlexiev** [comment]
@dgarijo great! Can you put the tests in this repo, so I can take a more detailed look? 

> 1. takes them as named individuals

And forgets that they are properties? 

I use the following makefile (it uses Saxon and my patched version of `extraction.xsl` directly since I can't build LODE):
```
index.html: ebg-ontology.rdf extraction.xsl
	transform -xsl:extraction.xsl -s:ebg-ontology.rdf -o:index.html

ebg-ontology.rdf: ../model/ebg-ontology.ttl
	riot --output=rdfxml ../model/ebg-ontology.ttl > ebg-ontology.rdf
```
`riot` collects all triples about a class in one XML element. But `extraction.xsl` produced only the namespace section, no classes nor properties ?!?

 2. I get the same: only classes, no properties:
```
transform -xsl:extraction.xsl -s:https://schema.org/Book.rdf -o:schema-book.html
```

**Comment by VladimirAlexiev** [comment]
Re 2 there are several spots to add `rdf:Property`:
```xml
    <xsl:template match="owl:ObjectProperty | owl:DatatypeProperty | owl:AnnotationProperty">
        <div id="{generate-id()}" class="entity">
            <xsl:call-template name="get.entity.name">
                <xsl:with-param name="toc" select="if (self::owl:ObjectProperty) then 'objectproperties' else if (self::owl:AnnotationProperty) then 'annotationproperties' else 'dataproperties'" tunnel="yes" as="xs:string" />
```
Unfortunately, for Schema it's not so easy to dispatch the props into 'objectproperties' vs 'dataproperties'. Options:
1. examine `rangeIncludes` and call it 'dataproperty' if the range includes only some of the 9 datatypes in https://schema.org/docs/full.html#datatype_tree: `schema:Boolean, Date, DateTime, Number, Float, Integer, Text, URL, Time`
2. put `rdf:Property` in a new section 'Properties' (for Schema, only that section will appear)
3. leave it as is, then all Schema props will be called 'dataproperties'

I think option 2 is the best since 1 will require schema-specific hardcoding, wheres 3 is misleading

**Comment by dgarijo** [comment]
Hi @VladimirAlexiev,
I have added the 2 examples I used to test it out,  including my edited version of    http://data.businessgraph.io/ontology to avoid the issue mentioned (see https://github.com/dgarijo/Widoco/commit/ed5c97d35cc372de3cf3e89646ea296156f2aea0)

I am pushing to the develop branch, so please use the extraction.xsl file from there. Based on your second comment, I think you may not have seen it. I edited the rdf:Property in each of the 17 locations where objectProperty appears, but it still doesn't add them as an objectProperty. In my case, I was assuming that all rdf:Property would have the same behavior as ObjectProperty, but you are right, they can be both datatype properties and object properties. I am going to remove my edits to the file and keep the support only for owl:objectProperty and owl:datatypeProperty. Going for option 2 would be ideal, but I will leave it for the future.

**Comment by dgarijo** [comment]
https://github.com/dgarijo/Widoco/commit/65f9433e169abe67752a7d4fa95b1450f0f58186 is the commit that had my rdf:Property additions in case you are interested.
