### ISSUE TITLE
Unable to generate documentat for the ontology adms.rdf

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#539]
**Describe the bug**

Error generating the documentation for this ontology: https://github.com/ahmad88me/ontologies_gister/blob/main/Top_in_lov/adms.rdf

Widoco version: `widoco-1.4.16-jar-with-dependencies.jar`

**Comment by dgarijo** [comment]
Should toy around with the generation properties so if a literal is malformed, not the whole process works.

**Comment by ahmad88me** [comment]
Thanks

**Comment by dgarijo** [comment]
@ahmad88me I have been digging in this issue. Widoco is able to load the ontology, but we do an intermediate transformation that requires the ontology to be well formed. This is a requirement by the OWLAPI. Hence, I am closing the issue. The solution to this issue is to make sure the ontology is well formed.
