### ISSUE TITLE
Include owl:equivalentClass in the documentation

### ISSUE THREAD

**Issue by larswik** [dgarijo/Widoco#567]
**Is your feature request related to a problem? Please describe.**
I would like to document an alignment ontology that uses owl:equivalentClass/owl:equivalentProperty statements. However, these triples seem to be disregarded ("Unparsed triple" in the log)

**Describe the solution you'd like**
It seems like rdfs:subClassOf/rdfs:subPropertyOf and owl:sameAs (also used in ontology alignment) are documented (e.g. "has super classes", "Is same as", ...). Can resource equivalence be documented in a similar fashion?

**Describe alternatives you've considered**
None

**Additional context**
-

**Comment by dgarijo** [comment]
It should be possible, I will have to take a look.

**Comment by dgarijo** [comment]
I have been looking at this issue, and equivalence is recognized and documented. The only "issue" I see is that in some cases the equivalence id documented in the other class rather than in the main one. For example:
```
###  https://w3id.org/example#Organization
:Organization rdf:type owl:Class ;
              <http://purl.org/vocab/vann/example> "University of Southern California"@en ;
              rdfs:comment "An organized body of people with a particular purpose, especially a business, society, association, etc."@en ;
              owl:equivalentClass <http://xmlns.com/foaf/0.1/Organization>;
              rdfs:label "Organization"@en 
```
will show the organization class as is, and in foaf:Organization the equivalence (this is the simplified html):
```
organization c back to ToC or Class ToC

IRI: http://xmlns.com/foaf/0.1/Organization

is equivalent to
    Organization c # Link to your class
```
I believe this is due to how the OWLAPI represents concepts underneath (it's technically the same). I verified that the logic of the XSLT is correct, so I am closing the issue
