### ISSUE TITLE
Add skos:editorialNote in the generated documentation

### ISSUE THREAD

**Issue by fsutter** [dgarijo/Widoco#592]
Hi,

I've a lot of skos:editorialNote annotations in my RDF.
Is it possible to have them displayed in the generated documentation?
If so, how?

Many thanks in advance and kind regards,

**Comment by dgarijo** [comment]
@fsutter,
it's quite simple to add the property, but you need to extend the xslt file for conversions. What would be the header of the property? `editorial note`?

**Comment by fsutter** [comment]
Great, when is the next release planed?
Thanks

**Comment by dgarijo** [comment]
When I have the time :)
It's going to take a bit, since I just did a release last week.

**Comment by andre-hui** [comment]
Hello! Just wondering, would it be very taxing to add in a config file or similar which can be edited to determine which properties (and their labels) are generated? For example, being able to also generate skos:scopeNote would be really helpful.

See https://www.ica.org/standards/RiC/RiC-O_v0-2.html for what I mean by a custom property that was generated in the html ("Mapping to to RiC-CM v0.2")

**Comment by dgarijo** [comment]
@andre-hui,
Widoco uses a xslt transformation to go from owl into html (based on LODE). So in order to add new custom properties, you'd have to edit the xslt mapping file. Devising a flexible mechanism to include custom properties so they are edited in the xslt on the fly so everything work is not trivial. Plus, the labels to all supported languages would also have to be declared. If you do it in the ontology, then you would have to filter afterwards the corresponding individuals so they don't appear in the documentation.

**Comment by andre-hui** [comment]
> 

Thanks for letting me know! Appreciate that you took the time to reply.

**Comment by dgarijo** [comment]
I'll provide some insight int how to edit the xslt to support your own stuff.
