### ISSUE TITLE
XML version is not generated

### ISSUE THREAD

**Issue by ahmad88me** [dgarijo/Widoco#643]
**Describe the bug**

**To Reproduce**
java -jar widoco-1.4.20-jar-with-dependencies_JDK-17.jar -ontFile BFiaO.owl -outFolder out -saveConfig w.config -lang en -htaccess 

**Expected behavior**
To find ontology.xml inside the output folder `out`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Java Version: JDK 21
 - Version: Widoco 1.4.20
 - Used ontology: https://github.com/ahmad88me/bfiao/blob/main/BFiaO.owl

**Additional context**
The ontology.xml has html and is not located in the specified output folder (it was in the working directory instead)

**Comment by dgarijo** [comment]
Will have a look

**Comment by dgarijo** [comment]
@ahmad88me I have detected why this is. Instead of producing an `xml` file, we now call it an `owl`. This is because most ontologies use as `owl` the rdf/xml serialization. For example, the one you just used in your example :)

So, the file is there, it's just `.owl` now. 
![image](https://github.com/dgarijo/Widoco/assets/1520666/eddb4edd-dbb4-4100-b051-a97326b6090a)

Closing the issue.
