### ISSUE TITLE
Documentation not created

### ISSUE THREAD

**Issue by lucaturchet** [dgarijo/Widoco#706]
I have issues with the generation of the documentation. My owl file loads with no errors (please find it attached)
[MUSICO_light.owl.txt](https://github.com/user-attachments/files/15537377/MUSICO_light.owl.txt)
However, when I generate the documentation I only get a few sections. I loaded as .txt files the abstract, description and references but these are not included. The VOWEL visualization is not integrated. If I check the html file in the related folder I get the error "Failed to load: ontology ERROR STATUS: 0". Finally, the SWRL rules are not displayed.

I am on a MacOS. I run the latest release with JDK 17.

**Comment by dgarijo** [comment]
I don't get an error generating the documentation.

The failed to load error is usually seen when you open your ontology doc locally instead of putting it in a server (that usually fixes the issue), if you put it in github, e.g., through github pages, you will be able to see it fine. For example, I put it in a test repo and I can see everything fine: http://dgarijo.github.io/test/musico/index-en.html

Related doc: https://github.com/dgarijo/Widoco?tab=readme-ov-file#browser-issues-why-cant-i-see-the-generated-documentation--visualization

**Comment by dgarijo** [comment]
And the SWRL rules seem also fine. It looks like you just need to properly serve the doc

**Comment by lucaturchet** [comment]
Thanks. I have my owl file online, but when I load it via widoco I get the error that "The ontology could not be loaded". If I use the local file it can bel loaded and passes the synthax checks.

The file is accessible here: https://github.com/lucaturchet/musico/blob/master/MUSICO_light.owl

Any idea? As I mentioned, I am on a MacOS. I am running the latest release with JDK 17.

**Comment by dgarijo** [comment]
Yes, that happens because https://github.com/lucaturchet/musico/blob/master/MUSICO_light.owl is not an OWL file. It is an HTML file. The owl file is at https://raw.githubusercontent.com/lucaturchet/musico/master/MUSICO_light.owl

**Comment by lucaturchet** [comment]
Thanks!

**Comment by dgarijo** [comment]
@lucaturchet sorry, is this another error?

**Comment by lucaturchet** [comment]
no it is the very same one, replicated using the URL instead of the local file

**Comment by dgarijo** [comment]
you have to use the raw.github link, not the github link

**Comment by lucaturchet** [comment]
Yes I am using it. This one to clarify https://raw.githubusercontent.com/lucaturchet/musico/master/MUSICO_light.owl

**Comment by dgarijo** [comment]
So the URL works, the documentation is generated, and in order to host it, you should set up a server, as I said in my original response.

**Comment by lucaturchet** [comment]
Thanks now I understand. Then I would suggest to amend the final page of the software stating to visualize the result on the browser, just my five cents

**Comment by dgarijo** [comment]
@lucaturchet that's why we have https://github.com/dgarijo/Widoco?tab=readme-ov-file#browser-issues-why-cant-i-see-the-generated-documentation--visualization. I would not want to pollute the final documentation, since that would make everyone have to go back and delete the warning. Unless there is a way of detecting that the content could not be loaded in javascript, and show an alert (I am not sure if it's possible). Thanks!

**Comment by dgarijo** [comment]
The documentation generates the webvowl visualization (http://dgarijo.github.io/test/musico/index-en.html is generated with the latest version). It looks like you modified the introduction section and removed it.

**Comment by dgarijo** [comment]
I removed serving the doc from the test repository

**Comment by lucaturchet** [comment]
Thanks a lot for your patience, now it all works.
